const menu: menuItem[] = [
    {name: "Crispy Chicken Sandwich", price: "$15.00", description: "Marinated to perfection, our Breaded fried Chicken Breasts with mouth melting Honey Mustard sauce, comes with lettuce and tomatoes", image_url: `images/Crispy Chicken Sandwich.jpg`},
    {name: "Crispy Chicken Nuggets", price: "$9.99", description: "8 Deep fried Marinated Chicken Pieces", image_url: getRandomImage()},
    {name: "Burger", price: "$14.00", description: "House Grounded Prime Beef burger, Char broiled, topped with our Tasty special sauce comes with lettuce and tomatoes", image_url: getRandomImage()},
    {name: "Parve Cheese Beef Burger", price: "$16.99", description: "House Grounded Prime Beef burger, Char broiled, topped with our Tasty special sauce comes with lettuce and tomatoes", image_url: getRandomImage()},
    {name: "BBQ Steak Sub", price: "$20.99", description: "Our Prime Ribeye thinly sliced to perfection, stir fried with sweet caramelized onions topped with BBQ sauce on a toasted New York sub", image_url: getRandomImage()},
    {name: "Basic Hot Dog", price: "$4.49", description: "Ballpark style Franks, served on a steamed New York bun comes with ketchup and mustard", image_url: getRandomImage()},
    {name: "Slaw Dog", price: "$6.49", description: "Ballpark style Franks, served on a steamed New York bun comes with our house made sweet coleslaw and ketchup and mustard", image_url: getRandomImage()},
    {name: "Small Fries", price: "$3.99", description: "", image_url: getRandomImage()},
    {name: "Large Fries", price: "$7.99", description: "", image_url: getRandomImage()},
    {name: "Sprite", price: "$1.99", description: "", image_url: getRandomImage()},
    {name: "Diet Coke", price: "$1.99", description: "", image_url: getRandomImage()},
    {name: "Coke", price: "$1.99", description: "", image_url: getRandomImage()},
    {name: "Pastrami Egg Rolls", price: "$5.99", description: "Our signature egg rolls filled with smoked pastrami and served with spicy sauce", image_url: getRandomImage()},
    {name: "Shawarma Spiced Pargiot", price: "$21.99", description: "A flavorful Middle Eastern dish of lamb skewers topped with spiced parghiot rice and Israeli salad", image_url: getRandomImage()},
    {name: "Rice", price: "$4.99", description: "Steamed rice", image_url: getRandomImage()},
    {name: "Corn Dog", price: "$6.49", description: "A juicy corn dog coated in a sweet and spicy sauce", image_url: getRandomImage()},
    {name: "Beef Tacos", price: "$5.99", description: "Tender ground beef topped with lettuce, tomato, and shredded cheese", image_url: getRandomImage()},
    {name: "Israeli Salad", price: "$4.99", description: "A colorful mixed greens salad with tomatoes, cucumbers, carrots, and cucumbers", image_url: getRandomImage()},
    {name: "Tortilla Chips", price: "$5.99", description: "Salted tortilla chips with Gwacomoli or salsa", image_url: getRandomImage()},
]
